version: '3.1'

services:

  wordpress:
    build:
      context: ./dockerfiles
      dockerfile: wordpress.dockerfile
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./env/wordpress.env
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: